### ISSUE TITLE
Does this arch log GPT-4 queries?

### ISSUE THREAD

**Issue by SeaDude** [j-d-harvey/OpenAItemplates#26]
Hello,

GPT-4 context window is 8-32k tokens. At 8kb max, App Insights logging capacity per event is unable to log prompts and responses that exceed this. 

Is there a way to use your solution and an APIM EventGrid logger to capture these larger token events?

Thank you

**Comment by j-d-harvey** [comment]
Hello,

You can find an example of how to deploy an EventGrid logger with an ARM template here: https://github.com/Azure-Samples/openai-python-enterprise-logging/blob/main/advanced-logging/README.md. You could convert that template to Bicep for reference and then replace or update the apimLogger resource in the apimanagement.bicep module in my repo.

Another alternative would be to save chat history to a Cosmos database in your application code. An example of how to do that can be found in the UI code for deploying Azure OpenAI on your data at https://github.com/microsoft/sample-app-aoai-chatGPT.

Hope that helps?

**Comment by j-d-harvey** [comment]
Closing, but happy to answer any other questions.
